spring.application.name=todoappweb

# MySQL接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/todoapp
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#メール設定
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin-email=${ADMIN_EMAIL}

#アプリケーションURL設定
app.base-url=${APP_BASE_URL:http://localhost:8080}